on: [push]

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ./
        with:
          project-name: 'test-project'
          task: 'init'

      - name: copy contract
        run: |
          ls -l ./ 
          sudo cp contracts/counter.jsligo test-project/contracts/
          cd test-project
          sudo npm init -y
          sudo chown -R runner:docker ./
          ls -l ./
          cd ..
      - name: install the ligo plugin
        uses: ./
        with:
          project-name: 'test-project'
          # task: 'install @taqueria/plugin-ligo-0.0.0-pr-704-cbcdf9ce'
          task: 'install @taqueria/plugin-ligo@0.0.0-pr-704-cbcdf9ce'

      - name: compile the contracts
        uses: ./
        with:
          project-name: 'test-project'
          task: 'compile'
        env:
          PROJECT_DIR: /home/runner/work/taqueria-github-action/taqueria-github-action/new-plugin-project
