on: [push]

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: 'test-project'
          task: 'init'
          args: '-v "/github:/github"'

      - name: initialize node
        run: |
          sudo chown -R runner:docker test-project
          cp contracts/counter.jsligo test-project/contracts/
          cd test-project
          id
          ls -ltra ./
          npm init -y
          cd ..

      - name: install the ligo
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: 'test-project'
          task: 'install @taqueria/plugin-ligo'
          args: '-v "/github:/github"'

      - name: install the ligo
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: 'test-project'
          task: 'compile'
          args: '-v "/github:/github"'