on: [push]

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:
      - name: taq init step
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: 'test-project'
          task: 'init'