on: [push]

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: '/github/workspace'
          task: 'init'

      - name: initialize node
        run: |
          sudo chown -R runner:docker /github/workspace
          ls -ltra ./
          npm init -y

      - name: install the ligo
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: '/github/workspace'
          task: 'install @taqueria/plugin-ligo'

      - name: install the ligo
        uses: ecadlabs/taqueria-github-action@v0.0.1-rc1
        with:
          project-name: '/github/workspace'
          task: 'compile'